### ISSUE TITLE
Importar librerías en la función de testeo

### ISSUE THREAD

**Issue by mantiagosartinez** [githubuali/ml_uali#1]
¿Dentro de la función de testeo importamos las librerías? No suele ser común importarlas dentro de una función pero si se quiere testear es más facil. Además en ningún otro caso se va a utilizar la función de testeo.

(Hago esto como prueba de Issue ya que es la primera vez que hago uno, también para proponer una metodología de uso)

**Comment by maxiyommi** [comment]
No lo veo mal! si no son muy pesadas, no veo el problema.
